package com.suraj.CarSearch;

import java.util.HashSet;
import java.util.Set;
import java.util.SortedSet;
import java.util.TreeSet;

public class InternHomework 
{
	public static final Set<CarResult> CARS;
	static{
		    CARS = new HashSet<>();		
		    CARS.add(new CarResult("SIXT", "Peugeot 107", "MCMR", 22.50, CarResult.FuelPolicy.FULLFULL));
		    CARS.add(new CarResult("AVIS", "Peugeot 107", "MCMR", 30.05, CarResult.FuelPolicy.FULLFULL));
		    CARS.add(new CarResult("SIXT", "OPEL corsa ", "MDMN", 29.50, CarResult.FuelPolicy.FULLEMPTY));
		    CARS.add(new CarResult("FIREFLY", "Peugeot 107", "MCMR", 21.50, CarResult.FuelPolicy.FULLFULL));
		    CARS.add(new CarResult("DELPASO ", "Peugeot 107", "MCMR", 23.50, CarResult.FuelPolicy.FULLFULL));
		    CARS.add(new CarResult("GOLDCAR ", "Peugeot 107", "MCMR", 20.50, CarResult.FuelPolicy.FULLEMPTY));
		    CARS.add(new CarResult("RECORD ", "Peugeot 107", "MCMR", 24.20, CarResult.FuelPolicy.FULLFULL));
		    CARS.add(new CarResult("SIXT", "BMW 3", "MCMR", 22.50, CarResult.FuelPolicy.FULLFULL));
		    CARS.add(new CarResult("SURAJ", "Volkswagen Polo", "EDMR", 12.81, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("SURAJ", "Ford C-Max Diesel", "CMMD", 27.09, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("SURAJ","Renault Scenic Diesel",  "JGAD", 90.34, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("SURAJ","Volkswagen Up",  "MDMR", 9.05, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("SURAJ","Volkswagen Golf",  "CDMR", 15.37, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("SURAJ","Audi A3 Diesel",  "CDMD", 67.73, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("SURAJ","Volkswagen Touran Diesel",  "IVMD", 76.33, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("SURAJ","Mini Cooper",  "EDMR", 16.75, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("SURAJ","BMW 2 Series Gran Tourer Diesel",  "JVAD", 146.62, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("SURAJ","Volkswagen Polo",  "EDMR", 12.55, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("SURAJ","Ford C-Max Diesel",  "CMMD", 33.10, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("SURAJ","Renault Scenic Diesel",  "JGAD", 15.59, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("SURAJ", "Volkswagen Up", "MDMR", 18.6, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("SURAJ","Volkswagen Golf",  "CDMR", 36.06, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("SURAJ", "Audi A3 Diesel", "CDMD", 67.07, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("SURAJ","Volkswagen Touran Diesel", "IVMD", 77.41, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("SURAJ","Mini Cooper",  "EDMR", 37.00, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAJESH","Citroen Berlingo",  "CMMV", 27.67, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAJESH","Ford Focus Estate Diesel",  "CWMD", 71.12, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAJESH","Volkswagen Golf",  "CDMR", 26.96, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAJESH", "Ford Fiesta Diesel", "EDMD", 25.02, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAJESH","Nissan Juke Diesel",  "HFMD", 31.31, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAJESH","Volkswagen Golf Diesel",  "CDMD", 3.91, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAJESH","Ford C-Max Diesel",  "CMMD", 54.34, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAJESH", "Volkswagen Touran", "IVAR", 56.87, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAJESH","Volkswagen Polo",  "EDMR", 23.89, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAJESH","Ford Focus Estate",  "CWMR", 98.32, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAJESH","Ford Galaxy Diesel",  "FVMD", 67.89, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAJESH","Mercedes Vito Traveliner",  "SVMR", 63.56, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAJESH","Volkswagen Touran",  "IVMR", 60.64, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAJESH","Volkswagen Touran Diesel",  "IVMD", 88.43, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAJESH", "Peugeot 107", "MCMR", 5.93, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAJESH","Citroen Berlingo",  "CMMV", 65.45, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAJESH","Ford Focus Estate Diesel",  "CWMD", 54.27, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAJESH","Volkswagen Golf",  "CDMR", 58.77, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAJESH","Ford Fiesta Diesel",  "EDMD", 56.77, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult( "RAJESH","Nissan Juke Diesel", "HFMD", 67.35, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAJESH","Volkswagen Golf Diesel",  "CDMD", 23.89, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAJESH","Ford C-Max Diesel",  "CMMD", 111.27, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAJESH","Volkswagen Touran",  "IVAR", 34.79, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAJESH","Volkswagen Polo",  "EDMR", 433.41, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAJESH","Ford Focus Estate",  "CWMR", 91.89, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAJESH","Ford Galaxy Diesel",  "FVMD", 18.89, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAJESH","Mercedes Vito Traveliner",  "SVMR", 199.62d, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAJESH","Volkswagen Touran",  "IVMR", 105.45d, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAJESH","Volkswagen Touran Diesel",  "IVMD", 113.83d, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAJESH", "Peugeot 107", "MCMR", 40.82, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAJESH","Citroen Berlingo",  "CMMV", 40.10, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAJESH","Ford Focus Estate Diesel",  "CWMD", 90.23, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAJESH","Volkswagen Golf",  "CDMR", 26.89, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAJESH","Ford Fiesta Diesel",  "EDMD", 25.00, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult( "RAJESH","Nissan Juke Diesel", "HFMD", 35.31, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAJESH", "Volkswagen Golf Diesel", "CDMD", 12.19, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAJESH","Ford C-Max Diesel",  "CMMD", 71.23, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAJESH","Volkswagen Touran",  "IVAR", 102.75, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAJESH", "Volkswagen Polo", "EDMR", 11.38, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAJESH","Ford Focus Estate",  "CWMR", 60.86, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAJESH","Ford Galaxy Diesel",  "FVMD", 123.63, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAJESH","Mercedes Vito Traveliner",  "SVMR", 158.59, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RRAJESHjesh","Volkswagen Touran",  "IVMR", 74.42, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAJESH","Volkswagen Touran Diesel",  "IVMD", 82.8, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAJESH","Peugeot 107", "MCMR", 9.78, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("GOLDCAR","Toyota Avensis",  "IDMR", 301.95, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("GOLDCAR","Nissan Juke",  "CFMR", 146.54, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("GOLDCAR","Volkswagen Golf",  "CLMR", 52.02, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("GOLDCAR","Citroen C4 Grand Picasso",  "IVAR", 399.28, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("GOLDCAR","Toyota Avensis",  "IDAR", 116.68, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("GOLDCAR","Ford Focus Estate",  "CWMR", 12.45, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("GOLDCAR","Volkswagen Touran",  "IVMR", 36.8, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("GOLDCAR","Citroen DS3",  "ESMR", 63.6, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("GOLDCAR","Audi A3",  "ICMR", 84.46, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("GOLDCAR","Citroen Berlingo",  "CMMV", 53.89, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("GOLDCAR","Volkswagen Polo",  "EDMR", 131.71, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("GOLDCAR", "Renault Scenic", "JGMR", 19.95, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("GOLDCAR","BMW 3 Series",  "FDAR", 43.43, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("GOLDCAR","Peugeot 107",  "MCMR", 26.86, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("GOLDCAR","Mercedes Vito Traveliner",  "SVMR", 62.17, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("GOLDCAR","Volkswagen Golf",  "CDMR", 39.79, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("GOLDCAR","Toyota Avensis",  "IDMR", 243.55, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("GOLDCAR","Nissan Juke",  "CFMR", 127.3, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("GOLDCAR","Volkswagen Golf",  "CLMR", 54.13, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("GOLDCAR","Citroen C4 Grand Picasso",  "IVAR", 326.7d, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("GOLDCAR","Toyota Avensis",  "IDAR", 97.31, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("GOLDCAR","Ford Focus Estate",  "CWMR", 114.01, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("GOLDCAR","Volkswagen Touran",  "IVMR", 303.43, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("GOLDCAR","Citroen DS3",  "ESMR", 60, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("GOLDCAR","Audi A3",  "ICMR", 74.04, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("GOLDCAR","Citroen Berlingo",  "CMMV", 70.83, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("GOLDCAR","Volkswagen Polo",  "EDMR", 44.99, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("GOLDCAR","Renault Scenic",  "JGMR", 120.59, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("GOLDCAR","BMW 3 Series",  "FDAR", 353.17, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("GOLDCAR","Peugeot 107",  "MCMR", 39.63, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("GOLDCAR","Mercedes Vito Traveliner",  "SVMR", 509.37, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("GOLDCAR","Volkswagen Golf",  "CDMR", 49.58, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAMESH","BMW 4 Series Convertible",  "RTAV", 189.85, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","Renault Megane Convertible",  "CTMR", 59.22, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","Citroen Berlingo",  "CMMV", 10.53, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","Ford Focus Estate",  "CWMR", 16.11, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","Volkswagen Passat Diesel",  "IDMD", 38.15, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","Renault Clio Estate",  "EWMR", 10.93, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","Mercedes Vito Traveliner",  "SVMR", 108.04, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","Volkswagen Polo",  "EDMM", 4.8, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","Ford Galaxy",  "FVMR", 45.07, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","BMW 3 Series",  "FDAR", 74.03, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","Volkswagen Touran",  "IVMR", 35.64, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","Volkswagen Golf Diesel",  "CDMD", 8.86, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH", "Toyota Yaris", "EDAR", 16.86, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","Volkswagen Up",  "MDMR", 4, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","Nissan Qashqai",  "IFMR", 45.07, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","Ford Fiesta Diesel",  "EDMD", 5.11, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","Toyota Avensis",  "IDMR", 36.57, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","Volkswagen Golf",  "CDMR", 8.05, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","Volkswagen Golf",  "CDAR", 22.24, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","Volkswagen Polo",  "EDMR", 40.49, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","Volkswagen Passat",  "SDAR", 34.22, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","BMW 3 Series",  "FDMR", 33.34, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","Mercedes Citan",  "CMMD", 15.344, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","BMW 4 Series Convertible",  "RTAV", 18.56, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","Renault Megane Convertible",  "CTMR", 59.22, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","Citroen Berlingo",  "CMMV", 10.53, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","Ford Focus Estate",  "CWMR", 16.11, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","Volkswagen Passat Diesel",  "IDMD", 38.15, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","Renault Clio Estate",  "EWMR", 10.93, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","Mercedes Vito Traveliner",  "SVMR", 108.04, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","Volkswagen Polo",  "EDMM", 4.8, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","Ford Galaxy",  "FVMR", 45.07, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH", "BMW 3 Series", "FDAR", 74.03, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","Volkswagen Touran",  "IVMR", 35.64, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","Volkswagen Golf Diesel",  "CDMD", 8.86, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult( "RAMESH","Toyota Yaris", "EDAR", 16.86, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","Volkswagen Up",  "MDMR", 43.00, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","Nissan Qashqai",  "IFMR", 45.07, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","Ford Fiesta Diesel",  "EDMD", 50.11, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","Toyota Avensis",  "IDMR", 38.45, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH", "Volkswagen Golf", "CDMR", 8.05, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","Volkswagen Golf",  "CDAR", 25.24, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","Volkswagen Polo",  "EDMR", 4.49, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH", "Volkswagen Passat", "SDAR", 44.14, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","BMW 3 Series",  "FDMR", 47.55, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","Mercedes Citan",  "CMMD", 10.53, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RAMESH","BMW 4 Series Convertible",  "RTAV", 516.52, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAMESH","Renault Megane Convertible",  "CTMR", 204.47, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAMESH","Citroen Berlingo",  "CMMV", 78.06, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAMESH","Ford Focus Estate",  "CWMR", 85.54, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAMESH","Volkswagen Passat Diesel",  "IDMD", 98.2d, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAMESH","Renault Clio Estate",  "EWMR", 82.37, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAMESH","Mercedes Vito Traveliner",  "SVMR", 231.59, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAMESH","Volkswagen Polo",  "EDMM", 70.89, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAMESH","Ford Galaxy",  "FVMR", 213.53, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAMESH","BMW 3 Series",  "FDAR", 199.93, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAMESH","Volkswagen Touran",  "IVMR", 168.28, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAMESH","Volkswagen Passat Diesel",  "IDAD", 127.59, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAMESH","Volkswagen Golf Diesel",  "CDMD", 76.94, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAMESH","Toyota Yaris",  "EDAR", 91.44, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAMESH", "Renault Scenic", "JGMR", 86.44, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAMESH","Volkswagen Up",  "MDMR", 54.43, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAMESH","Nissan Qashqai",  "IFMR", 8.47, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAMESH","Ford Fiesta Diesel",  "EDMD", 6, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAMESH","Toyota Avensis",  "IDMR", 9.78, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAMESH","Volkswagen Golf",  "CDMR", 75.1, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAMESH","Volkswagen Golf",  "CDAR", 79.5, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAMESH","Volkswagen Polo",  "EDMR", 74.44, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAMESH","Citroen C4 Cactus",  "CGAR", 101.45, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAMESH","Volkswagen Passat",  "SDAR", 90.78, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAMESH","BMW 3 Series",  "FDMR", 45.34, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAMESH","BMW 1 Series",  "IDAR", 172.81, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RAMESH","Mercedes Citan",  "CMMD", 78.06, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RECORD","Citroen Berlingo",  "CMMV", 33.26, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RECORD","Volkswagen Golf",  "CDMR", 26.52, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RECORD", "Nissan Juke", "CFMR", 28.64, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RECORD","Toyota Rav4",  "IFMR", 36.39, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RECORD","Ford Galaxy",  "FVMR", 14.09, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RECORD","Volkswagen Polo",  "EDMR", 22.23, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult( "RECORD","Peugeot 107", "MCMR", 119.1, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RECORD","Citroen Berlingo",  "CMMV", 34.8, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("RECORD", "Ford Galaxy", "FVAR", 60.75, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("SIXT","Audi A3",  "ICMR", 186.37, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("SIXT", "BMW 2 Series Active Tourer", "JDAR", 29.138, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("SIXT","Ford Focus Estate",  "CWMR", 24.56, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("SIXT","Volkswagen Polo",  "EDMR", 128.93, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("SIXT","Mercedes A Class",  "ICAV", 24.02, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("SIXT","Peugeot 107",  "MCMR", 97.08, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("SIXT","BMW 2 Series Active Tourer",  "JDMR", 183.14, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("SIXT","Smart Fortwo",  "MUMR", 115.76, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("SIXT", "Volkswagen Golf", "CDMR", 134.45, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("SIXT","Opel Corsa",  "ECMN", 107.58, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("SIXT","Mini Convertible",  "NTMR", 248.85, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("SIXT","Citroen C4 Cactus",  "CGAR", 191.54, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("SIXT","Mercedes E Class",  "PDAR", 3.22, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("SIXT", "Toyota Rav4", "IFAR", 38.62, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult( "SIXT","Mercedes E Class", "PDMR", 125.38, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("SIXT","Toyota Rav4",  "IFMR", 27.73, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("SIXT", "Volkswagen Passat Estate", "SWMR", 291.78, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("SIXT", "Ford Galaxy", "FVMR", 92.45, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("SIXT", "BMW 3 Series", "FDMR", 25.13, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("SIXT", "BMW 3 Series", "FDAR", 25.27, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("SIXT","Renault Scenic",  "JGMR", 25.09, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("AVIS","Toyota Avensis",  "IDMR", 33.69, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("AVIS","Opel Astra",  "CCMR", 23.32, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("AVIS","Volkswagen Touran Diesel",  "IVAD", 50.49, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("AVIS","Mercedes E Class",  "PDAR", 8.24, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("AVIS","Mercedes E Class",  "PDAR", 70.36, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("AVIS","Volkswagen Touran Diesel",  "IVMD", 95.74, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("AVIS","Skoda Octavia Diesel",  "IDMD", 30.22, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("AVIS","Ford Focus Estate",  "CWMR", 91.27, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("AVIS","Mercedes Viano",  "OVAR", 57.44, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("AVIS","Ford Galaxy Diesel",  "FVMD", 50.40, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("AVIS","Peugeot 107",  "MCMR", 145.52, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("AVIS","Toyota Avensis",  "IDAR", 45.34, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("AVIS","Volkswagen Polo",  "EDMR", 160.7, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("AVIS","Mercedes Vito Traveliner",  "SVMR", 64.38, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("AVIS","Mercedes A Class",  "ICAV", 30.56, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("AVIS","Volkswagen Golf Diesel",  "CDMD", 28.69, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("AVIS","Toyota Avensis",  "IDMR", 373.69, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("AVIS","Opel Astra",  "CCMR", 203.32, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("AVIS","Volkswagen Touran Diesel",  "IVAD",20.49, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("AVIS","Mercedes E Class",  "PDAR", 98.24, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("AVIS","Mercedes E Class",  "PDAR", 90.3, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("AVIS","Volkswagen Touran Diesel", "IVMD", 495.74, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("AVIS","Skoda Octavia Diesel", "IDMD", 30.22, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("AVIS","Ford Focus Estate",  "CWMR", 21.28, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("AVIS","Mercedes Viano",  "OVAR", 52.4, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("AVIS","Ford Galaxy Diesel", "FVMD", 20.49, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("AVIS","Peugeot 107", "MCMR", 145.52, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("AVIS","Toyota Avensis", "IDAR", 465.34, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("AVIS","Volkswagen Polo",  "EDMR", 160.73, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("AVIS","Mercedes Vito Traveliner",  "SVMR", 64.38, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("AVIS","Mercedes A Class",  "ICAV", 310.56, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("AVIS","Volkswagen Golf Diesel",  "CDMD", 58.69, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("BUDGET", "Toyota Avensis", "IDMR", 211.89, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("BUDGET", "Opel Astra",  "CCMR", 177.15d, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("BUDGET", "Volkswagen Golf",  "CDMR", 68.97, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("BUDGET", "Toyota Avensis",  "IDMR", 4.91, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("BUDGET", "Opel Astra",  "CCMR", 96.21, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("BUDGET", "Volkswagen Golf", "CDMR", 98.4, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("BUDGET", "Toyota Avensis",  "IDMR", 21.89, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("BUDGET", "Opel Astra",  "CCMR", 17.15, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("BUDGET", "Volkswagen Golf", "CDMR", 28.97, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("BUDGET", "Toyota Avensis", "IDMR", 21.89, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("BUDGET", "Opel Astra", "CCMR", 77.15, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("BUDGET", "Volkswagen Golf", "CDMR", 68.97, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("BUDGET", "Toyota Avensis", "IDMR", 21.89, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("BUDGET", "Opel Astra",  "CCMR", 77.15, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("BUDGET", "Volkswagen Golf",  "CDMR",68.97, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("Ford Focus Estate", "DELPASO", "CWMR", 31.35, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("DEADPOOL","Volkswagen Up",  "MDMR", 5.92, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("DEADPOOL","Volkswagen Golf",  "CDMR", 11.49, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("DEADPOOL","Toyota Rav4", "IFMR", 41.16, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("DEADPOOL","Volkswagen Polo", "EDMR", 6.23, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("DEADPOOL","Mercedes Vito Traveliner", "SVMR", 121.26, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("DEADPOOL","Peugeot 107", "MCMR", 5.92, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult( "THRIFTY","Peugeot 107", "MCMR", 67.0, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult( "THRIFTY","Peugeot 107",  "MCMR", 67.03, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult( "THRIFTY","Renault Clio Estate",  "EWMR", 45.16, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult( "FIREFLY","Peugeot 107",  "MCMR", 26.57, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("FIREFLY", "Volkswagen Polo",  "EDMR", 29.79, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("FIREFLY","Citroen Berlingo",  "CMMV", 35.67, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("FIREFLY","Volkswagen Touran",  "IVMR", 125.9, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("FIREFLY","Volkswagen Golf",  "CDMR", 33.84, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("HERTZ","Peugeot 107",  "MCMR", 67.98, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("HERTZ","Peugeot 107", "MCMR", 60.34, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("ENTERPRISE","Peugeot 107",  "MCMR", 78., CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("ENTERPRISE","Volkswagen Passat", "SDMR", 26.5, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("ENTERPRISE","Volkswagen Polo", "EDMR", 105.51, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("ENTERPRISE","Ford Galaxy", "FVMR", 52.95, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("ENTERPRISE","Volkswagen Touran", "IVAR", 92.35, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("ENTERPRISE","Citroen Berlingo", "CMMV", 12.23, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("ENTERPRISE","Toyota Avensis", "IDMR", 14.84, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("ENTERPRISE","Volkswagen Golf", "CDAR", 56.2, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("ENTERPRISE","Renault Scenic", "JGMR", 68.42, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("ENTERPRISE","Toyota Avensis", "IDAR", 43.05, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("ENTERPRISE", "Mercedes Vito Traveliner", "SVMR", 79.11, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("ENTERPRISE","Renault Scenic","IMMR", 24.74, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("ENTERPRISE","Volkswagen Golf", "CDMR", 42.05, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RHODIUM","Renault Scenic",  "JGMR", 80.47, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RHODIUM","BMW 3 Series", "FDAR", 49.68, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RHODIUM","Ford Focus Estate","CWMR", 177.09, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RHODIUM","Citroen DS3", "ESMR", 116.51, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RHODIUM","Volkswagen Golf","CDAR", 243.55, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RHODIUM","Volkswagen Golf", "CDMR", 104.53, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RHODIUM","Toyota Avensis", "IDMR", 300.00, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RHODIUM","Audi A3", "ICMR", 130.54, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RHODIUM","Citroen Berlingo", "CMMV", 114.01, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RHODIUM","Volkswagen Polo",  "EDMR", 92.9, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RHODIUM","Ford Galaxy","FVMR", 509.37, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RHODIUM","Volkswagen Golf", "CLMR", 109.76, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RHODIUM","Volkswagen Touran",  "IVMR", 359.93, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RHODIUM","Peugeot 107","MCMR", 87.36d, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RHODIUM","Volkswagen Touran", "IVAR", 383.03, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RHODIUM","Mercedes Vito Traveliner", "SVMR", 565.88, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("RHODIUM","Toyota Avensis", "IDAR", 153.82, CarResult.FuelPolicy.FULLFULL));
	        CARS.add(new CarResult("FLIZZR","Toyota Rav4", "IFMR", 75.93, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("FLIZZR","Opel Corsa", "EBMN", 49.29, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("FLIZZR","Peugeot 2008", "EGMR", 78.43, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("FLIZZR","Citroen C3 Picasso", "EMMV",25.33, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("FLIZZR","Volkswagen Golf", "CDMR", 90.93, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("FLIZZR","Volkswagen Polo", "EDMR", 23.00, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("FLIZZR","Citroen DS3", "ESMR", 13.90, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("FLIZZR","Citroen C1", "MBMR", 34.54, CarResult.FuelPolicy.FULLEMPTY));
	        CARS.add(new CarResult("FLIZZR","Toyota Rav4", "IFMR", 45.98, CarResult.FuelPolicy.FULLFULL));
	        
	}
	
	
    public static void main( String[] args )
    {
        ShowResults showResults= new ShowResults();
        
        showResults.render(CARS);
    }
}
